---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: data-service
  labels:
    app: data
spec:
  ports:
    - port: 3306
  selector:
    app: data
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
  labels:
    app: data
spec:
  selector:
    matchLabels:
      app: data
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
      - image: eon01/quotes-data:v1
        name: mysql
        env:
        - name: "MYSQL_USER"
          value: "root"
        - name: "MYSQL_PASSWORD"
          value: "root"
        - name: "MYSQL_DATABASE"
          value: "mydatabase"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "root"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
          subPath: mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
