version: "3"
services:
  back:
    image: oliverhu/quotes-back:v1
    volumes:
      - ./back/:/app
    ports:
      - "3000:3000"
    networks:
      - myapp

  data:
    container_name: data
    image: oliverhu/quotes-data:v1
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "mydatabase"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - myapp

networks:
  myapp:
